---

- hosts: node
  tasks:
  - name: Add the Oracle Java PPA to apt
    shell: add-apt-repository -y ppa:webupd8team/java

  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: install java
    apt: pkg=oracle-java8-installer update_cache=yes state=installed



